### ISSUE TITLE
Should I create a Forge version of this wishlist?

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#105]
Not much to say. Some people probably want certain Fabric mods on Forge. This one is the opposite.

**Comment by Martmists-GH** [comment]
If you want to go ahead, but it'd be treated separately from this.

**Comment by MagmaSlime123** [comment]
You didn't have to mark this as Invalid, was just a question...

**Comment by ehx-v1** [comment]
It's invalid because that would be a completely separate project and has no correlation whatsoever to this, except being inspired by it. As such, the question has no relevance for this repo.
