### ISSUE TITLE
Mod suggestion: JEI Utilities

### ISSUE THREAD

**Issue by ghost** [martmists-gh/fabric-mod-wishlist#115]
## Description

JEI Utilities is an enhancement mod for [JEI](https://www.curseforge.com/minecraft/mc-mods/jei). I am recommending a Fabric edition that provides similar features and capabilities to [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items).

### Features:

- [ ] shedaniel/RoughlyEnoughItems#1412
- [x] ~Recipes Record: When you add recipe output to the JEI bookmark, the current recipe will be recorded, and opening the recipe through the JEI bookmark will open the recorded recipe.~
> Recipe recording is already sort of implemented through pinning recipes, which in 8.4 will be able to be minimised down to just their output entries.
> https://github.com/shedaniel/RoughlyEnoughItems/issues/1410#issuecomment-1553436265
- [ ] ~Recipe Preview: Hold down `ctrl` to display a recipe preview of the recipe bookmark.~
> Recipe preview is also already a thing, albeit slightly differently, in that it will just show the first recipe with matching ingredients for any given favourite entry (if it exists); then again, in tandem with pinned recipes this basically allows for the same functionality.
> https://github.com/shedaniel/RoughlyEnoughItems/issues/1410#issuecomment-1553436265
- [ ] shedaniel/RoughlyEnoughItems#1413
- [ ] ~Bookmark Picker: Allows the player to use the middle mouse button to pick up bookmarks and put them in other positions.~
> And as for bookmark resorting, this is trivial in REI as all favourite entries are draggable by default.
> https://github.com/shedaniel/RoughlyEnoughItems/issues/1410#issuecomment-1553436265

## Details

- Does a Forge/Bukkit/etc version of this mod exist? `Yes`
    - If yes, what is the link to the GitHub/CurseForge/etc? https://www.curseforge.com/minecraft/mc-mods/jei-utilities
- Does a Fabric version of this mod exist for an older MC version? `No`

**Comment by Martmists-GH** [comment]
I believe this functionality is already [included in REI](https://www.reddit.com/r/feedthebeast/comments/uumg83/recipes_pinning_in_rei_when_you_need_to_prepare/) (listed as Favorites). In case this feature does not meet your requirements, I recommend opening an issue on the REI repository instead.

**Comment by ghost** [comment]
> I believe this functionality is already [included in REI](https://www.reddit.com/r/feedthebeast/comments/uumg83/recipes_pinning_in_rei_when_you_need_to_prepare/) (listed as Favorites). In case this feature does not meet your requirements, I recommend opening an issue on the REI repository instead.

This functionality is not included - the history section lists items you have recently viewed in any capacity through JEI, for example, viewing their recipe. Favourites does not do this. It is not a running history.

**Comment by ghost** [comment]
> > I believe this functionality is already [included in REI](https://www.reddit.com/r/feedthebeast/comments/uumg83/recipes_pinning_in_rei_when_you_need_to_prepare/) (listed as Favorites). In case this feature does not meet your requirements, I recommend opening an issue on the REI repository instead.
> 
> This functionality is not included - the history section lists items you have recently viewed in any capacity through JEI, for example, viewing their recipe. Favourites does not do this. It is not a running history.

I'll take your advice and go to their repo!

**Comment by ghost** [comment]
@Martmists-GH I've updated this issue to reflect the current status of each feature as it is being handled by the REI devs.

Would it make sense to reopen this issue simply to track the development of these feature integrations, for posterity?
