### ISSUE TITLE
Mod suggestion: Islands

### ISSUE THREAD

**Issue by Martmists-GH** [martmists-gh/fabric-mod-wishlist#2]
### Description

Quoting `Cannonfoddr (-_･) ︻デ═一 ▸#0411`:
> A world gen mod that allows players to create 'island biomes' 
> Basically it will produce a world that has nothing but islands but each island is just a single biome..
> Eg: 1 Island is a desert island, another is a jungle island - the next is plains
> The possible world gen options could be:
>- Biomes to include (desert/hill/jungle) 
> - Are varient allowed per island (taiga/taiga extreme hill etc) 
> - Min/max size of islands
> - Min/max distance between island
> This would mean you could have a lot of smaller islands close together or large island further apart or anything in between

### Details

- Does a Forge version of this mod exist? Yes (very similar)
    - If yes, what is the link to the github/curseforge? [survival-island-generator](https://www.curseforge.com/minecraft/mc-mods/survival-island-generator)
- Does a Fabric version of this mod exist for an older MC version? No

**Comment by Linguardium** [comment]
yes? https://www.curseforge.com/minecraft/mc-mods/fabric-survival-island
linked from curseforge's forge version page
