### ISSUE TITLE
Mod suggestion: BonsaiTrees

### ISSUE THREAD

**Issue by matty45** [martmists-gh/fabric-mod-wishlist#21]
### Description

A mod which adds a easier, lazier way to farm wood.

### Details

- Does a Forge version of this mod exist? Yes
    - If yes, what is the link to the github/curseforge? [bonsai-trees](https://www.curseforge.com/minecraft/mc-mods/bonsai-trees)
- Does a Fabric version of this mod exist for an older MC version? No

**Comment by Martmists-GH** [comment]
Plant in a Jar solves this.
