### ISSUE TITLE
Mod suggestion: Morph

### ISSUE THREAD

**Issue by matty45** [martmists-gh/fabric-mod-wishlist#25]
### Description

You can shapeshift into mobs you kill.

### Details

- Does a Forge version of this mod exist? Yes
    - If yes, what is the link to the github/curseforge? [morph](https://www.curseforge.com/minecraft/mc-mods/morph)
- Does a Fabric version of this mod exist for an older MC version? No

**Comment by immibis** [comment]
please no

**Comment by Juuxel** [comment]
This seems like [Requiem](https://www.curseforge.com/minecraft/mc-mods/requiem) with the Pandemonium expansion (bundled as an extra file on CurseForge).

**Comment by Martmists-GH** [comment]
Being able to transform into something else at will does seem quite a bit different, so I'll leave this open for now.

**Comment by JFronny** [comment]
There is also [Identity](https://www.curseforge.com/minecraft/mc-mods/identity) by Draylar now
