### ISSUE TITLE
Mod suggestion: Chisels & Bits

### ISSUE THREAD

**Issue by Martmists-GH** [martmists-gh/fabric-mod-wishlist#26]
### Description

A fabric port of Chisels & Bits

### Details

- Does a Forge version of this mod exist? Yes
    - If yes, what is the link to the github/curseforge? [chisels-bits](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)

**Comment by CoolMineman** [comment]
https://www.curseforge.com/minecraft/mc-mods/bits-and-chisels
