### ISSUE TITLE
Mod suggestion: datapack driven crafters e.g. furnaces or crafting tables

### ISSUE THREAD

**Issue by Nathan22211** [martmists-gh/fabric-mod-wishlist#30]
### Description

This mod would basically do what artis does but instead of a config file, the crafters that are created would be determined via files in the mod's data folders. e.g. a custom furnace's JSON, which is what would likely be used, would probably be something like
`{ 
    "crafter_type": "furnace"
    "fuel": [
            "(fuel items go here)
        ]
}`
that's more or less pseudo-code but you get the idea, the name of the block in (modID:name) would be determined by the location of the folder after data and the filename e.g. `data/survival/(whatever you'll use to separate crafter files)/oven.json` would be in-game as `survival:oven` and the recipe type would be determined like that too. e.g. this would turn out as `survival:oven_smelting`

### Details

- Does a Forge version of this mod exist? <yes/no>
    no
- Does a Fabric version of this mod exist for an older MC version? <yes/no>
    artis does something similar but it's done via a config, but doing it as I described, no

**Comment by Martmists-GH** [comment]
This seems like it would fit better in the [Artis](https://www.curseforge.com/minecraft/mc-mods/artis) mod or at [LibCD](https://www.curseforge.com/minecraft/mc-mods/libcd).
Overall this request is too vague currently and needs cleaning up before we can categorize it.
