### ISSUE TITLE
Mod suggestion: Endergetic Expansion

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#31]
### Description

Some sort of End enhancement mod.

### Details

- Does a Forge version of this mod exist? Yes
    - If yes, what is the link to the github/curseforge? [endergetic](https://www.curseforge.com/minecraft/mc-mods/endergetic)
- Does a Fabric version of this mod exist for an older MC version? No

**Comment by Martmists-GH** [comment]
Edited issue; For Nether content have a look at [betternether](https://www.curseforge.com/minecraft/mc-mods/betternether)

**Comment by MagmaSlime123** [comment]
Ik about that mod. But there is no Fabric port for NetherEx.

**Comment by Martmists-GH** [comment]
Open a separate issue for that mod then, though I doubt anyone will do a 1:1 port when BetterNether already exists.

**Comment by ghost** [comment]
There is an end enhancement mod for Fabric and it’s called End: Rebellion. You can get it here https://www.curseforge.com/minecraft/mc-mods/end-rebellion

**Comment by BartTerpstra1** [comment]
has been made: https://www.curseforge.com/minecraft/mc-mods/betterend

**Comment by MagmaSlime123** [comment]
Like NetherEx, this would be nice to have rather then being forced to use BetterEnd, End Rebellion or BYG.

Choosing is a thing.
