### ISSUE TITLE
Mod suggestion: Customizable Gravity 

### ISSUE THREAD

**Issue by SirBlackEnergy** [martmists-gh/fabric-mod-wishlist#41]
### Description
Ever feel that the end should have a lower gravitational force that the overworld? Or the nether needs to their gravitational force much higher to feel the pain? With /Grav you can set the gravitational force to your liking 
### Details
Adds Gravitational manipulation command so it reacts in all 3 Axis with different dimensions having different gravitational force (end have more lower gravitational pull than the overworld and the nether having more gravitational pull that the overworld) also allows the player / moderators to change the gravitational force with the command `/grav 0 1 0` (so 1 is default and the order of the command is similar to X Y Z) and the pre built gravity `/grav overworld/Nether/End/Moon/None/Hardcore`

**Comment by Martmists-GH** [comment]
Please rewrite to match the template
