### ISSUE TITLE
Mod suggestion: More Screenshot's

### ISSUE THREAD

**Issue by SirBlackEnergy** [martmists-gh/fabric-mod-wishlist#42]
### Description
Wanted a birds eye view of the magnificent build you just made? But can't use /fly or it's too big in one shot? Say no more with this bundle of screenshot options 

### Details
adds more screenshot's options before saving it, from adding filters to your own shader-ish look, adding isometric view support in North, south, east and west, adding save to clipboard/copy, adding HI -RES option that will optimise the screenshot details.

**Comment by Martmists-GH** [comment]
Please rewrite to match the template
