### ISSUE TITLE
Mod suggestion: GUI customisation

### ISSUE THREAD

**Issue by SirBlackEnergy** [martmists-gh/fabric-mod-wishlist#43]
### Description

Wanted to remove some parts of the GUI but keeping the other parts?, Wanted to enhance the GUI by customizing it to look like another game GUI? 
### Details
moveable and removeable Gui elements, having the option to move your subtitles (or even modify the looks to make it source like), resize the potion effects, and even moving where the hotbar is located (of adding hide hotbar until usage) with moving it with your own mouse or normal sliders and numbers, positioning the health, hunger and armor bars somewhere else

**Comment by Martmists-GH** [comment]
Please rewrite to match the template

**Comment by Madis0** [comment]
Related: https://ftb.gamepedia.com/Advanced_HUD
