### ISSUE TITLE
Mod suggestion: fog-of-war protection against x-ray

### ISSUE THREAD

**Issue by sdaugherty** [martmists-gh/fabric-mod-wishlist#51]
### Description

Paper has one of the most effective anti-xray protections available, in the form of a protocol translating layer, whereby the server simply lies to the client about the blocks the player can't see, reporting the presence of either worthless blocks such as stone and wood, or completely random block in their place in order to effectively blind players from seeing valuables using xray resource packs until those blocks are actually in unobstructed line of sight.

This makes for both a very effective and efficient protection, akin to a serverside "fog of war", at least with respect to valuables.

### Details

- Does a Forge version of this mod exist? no
    - If yes, what is the link to the github/curseforge? n/a
- Does a Fabric version of this mod exist for an older MC version? afaik, no
    - If yes, what is the link to the github/curseforge? n/a

**Comment by Martmists-GH** [comment]
@Hephaestus-Dev was working on something like this: [Hephaestus-Dev/SAX](https://github.com/Hephaestus-Dev/SAX). Not sure what the status is on this.

**Comment by Haven-King** [comment]
On pause while I write a config API. Then it needs optimizations, but it's functional.
