### ISSUE TITLE
Mod suggestion: Biomes o' Plenty

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#65]
### Description

A big biome expansion mod for MC that adds 50 new biomes to the game, along with new ores, and much more!

### Details

- Does a Forge version of this mod exist? Yes.
    - If yes, what is the link to the github/curseforge? https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
- Does a Fabric version of this mod exist for an older MC version? No.
    - If yes, what is the link to the github/curseforge? N/A

**Comment by ramidzkh** [comment]
BoP works with Patchwork now

**Comment by Martmists-GH** [comment]
This repo does not accept Patchwork as solutions; There are likely to be issues, and BoP won't offer support for Patchworked mods. 

That said, Terrestria, Traverse, Cinderscapes, and more mods exist for Fabric, Adding dozens of biomes.

**Comment by MagmaSlime123** [comment]
Choosing is a thing.
