### ISSUE TITLE
Mod suggestion: iChun's PortalGun

### ISSUE THREAD

**Issue by LOuroboros** [martmists-gh/fabric-mod-wishlist#70]
### Description

A mod that implements many new items into Minecraft like a Portal Gun or a Falling Damage Negating pair of boots inspired by Valve's "Portal".

### Details

- Does a Forge version of this mod exist? <yes/no>
    - Yes. https://ichun.me/mods/portalgun/
- Does a Fabric version of this mod exist for an older MC version? <yes/no>
    - No.

**Comment by Martmists-GH** [comment]
[Thinking with Portatos](https://www.curseforge.com/minecraft/mc-mods/thinking-with-portatos)
