### ISSUE TITLE
Mod suggestion: Twilight Forest

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#75]
### Description

Adds a magical forest-like dimension with many new trees, bosses, mobs, building blocks, mobs, and MUCH, MUCH more.

### Details

- Does a Forge version of this mod exist? Yes.
    - If yes, what is the link to the github/curseforge? https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest
- Does a Fabric version of this mod exist for an older MC version? No.
    - If yes, what is the link to the github/curseforge? N/A

**Comment by Martmists-GH** [comment]
Closing as duplicate of #56

**Comment by MagmaSlime123** [comment]
Sorry.
