### ISSUE TITLE
Mod suggestion: CraftTweaker

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#81]
### Description

A custom recipe maker/remover/modification mod.

### Details

- Does a Forge version of this mod exist? Yep.
- If yes, what is the link to the github/curseforge? https://www.curseforge.com/minecraft/mc-mods/crafttweaker
- Does a Fabric version of this mod exist for an older MC version? No.
    - If yes, what is the link to the github/curseforge? N/A

**Comment by Martmists-GH** [comment]
KubeJS solves this issue.
