### ISSUE TITLE
Mod suggestion: LootTweaker (CraftTweaker Addon)

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#82]
### Description

A mod that lets you modify loottables via ZenScript files. The vanilla loot table system is limited to overriding existing loot tables or creating entirely new ones.

### Details

- Does a Forge version of this mod exist? Yep.
    - If yes, what is the link to the github/curseforge? https://www.curseforge.com/minecraft/mc-mods/loottweaker
- Does a Fabric version of this mod exist for an older MC version? No.
    - If yes, what is the link to the github/curseforge? N/A

**Comment by Martmists-GH** [comment]
Open as suggestion for KubeJS
