### ISSUE TITLE
Playing as a Bee (in retrospect this mod idea sucks lmao)

### ISSUE THREAD

**Issue by balt-dev** [martmists-gh/fabric-mod-wishlist#85]
### Description

You can set people to be bees with commands!
> /gamerule isBee <playername> <boolean> to turn on/off
> sleep in bee hives/nests
> base of 5 hearts
> your hunger is changed into honey drops, take nectar to the nest to refill them
> hold sneak near a flower to gain nectar
> you can fly like a bee (not creative flight, more like slow jetpack that propels both up and down + 0 gravity)
> you only have 2 water bubbles
> if you go into a nest with another bee, you become friends, and you can't damage them nor they damage you
> bee players can be bred with normal bees by normal players, but the player has to be near the other bee, and there's no special animation or anything lol
> nametags do show up above the bee

### Details

- Does a Forge version of this mod exist? No
- Does a Fabric version of this mod exist for an older MC version? No

**Comment by Martmists-GH** [comment]
Mostly provided by Requiem Pandemonium
