### ISSUE TITLE
Mod suggestion: Puddles

### ISSUE THREAD

**Issue by K0-RR** [martmists-gh/fabric-mod-wishlist#88]
Fabric port of this - https://www.curseforge.com/minecraft/mc-mods/puddles
Puddles. They would appear on solid blocks when it rains. You would be able to fill a glass bottle (this would play nicely with the Dehydration mod) from them and then a puddle would disappear. After rain and a few seconds/minutes they would vanish.

![102790758-3eaba300-43a6-11eb-9920-3a1c7501ba9a](https://user-images.githubusercontent.com/43277609/103046411-7114f600-4588-11eb-941b-26b500861f2f.png)

**Comment by DarkShadow44** [comment]
Does https://www.curseforge.com/minecraft/mc-mods/motschens-puddles fit here?
