### ISSUE TITLE
Don't stub your toe update to 1.17/18

### ISSUE THREAD

**Issue by K0-RR** [martmists-gh/fabric-mod-wishlist#95]
It's available for 1.14 fabric and 1.16 forge.

It makes you autojump while sprinting, even when autojumping is disabled in the game options. It is client-side only.

https://www.curseforge.com/minecraft/mc-mods/dont-stub-your-toe
https://github.com/Vexatos/dont-stub-your-toe

**Comment by IogaMaster** [comment]
I have made this mod now.

Just for 1.19, I will make a 1.17/1.18 version eventually.

https://modrinth.com/mod/dsyt

**Comment by IogaMaster** [comment]
Why is this done but not closed yet?
